---
# =============================================================
# host_vars/R3.yml — Variables específicas de R3
# =============================================================

hostname: "R3"

interfaces:
  wan:
    name: "GigabitEthernet0/0"
    ip: "10.0.0.3"
    mask: "255.255.255.0"
    description: "WAN - Red de gestion y transporte"
  lan:
    name: "GigabitEthernet0/1"
    ip: "192.168.3.1"
    mask: "255.255.255.0"
    description: "LAN local R3"

ospf_router_id: "3.3.3.3"

ospf_networks:
  - network: "192.168.3.0"
    wildcard: "0.0.0.255"
    area: 0
  - network: "172.16.13.0"
    wildcard: "0.0.0.3"
    area: 0
  - network: "172.16.23.0"
    wildcard: "0.0.0.3"
    area: 0

gre_tunnels:
  - name: "Tunnel31"
    number: 31
    local_ip: "172.16.13.2"
    mask: "255.255.255.252"
    source_interface: "GigabitEthernet0/2"
    destination: "192.168.13.1"
    description: "GRE R3 a R1"

  - name: "Tunnel32"
    number: 32
    local_ip: "172.16.23.2"
    mask: "255.255.255.252"
    source_interface: "GigabitEthernet0/1"
    destination: "192.168.23.1"
    description: "GRE R3 a R2"

ipsec_peers:
  - peer_ip: "192.168.13.1"
    tunnel_interface: "Tunnel31"
  - peer_ip: "192.168.23.1"
    tunnel_interface: "Tunnel32"
